version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "5269:5269"
    volumes:
      - csv-data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5269
  
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  admin:
    build:
      context: ./src/admin
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  csv-data:
